---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1 # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: nginx # Label to select pods for this deployment
  template:
    metadata:
      labels:
        app: nginx # Label for pods created by this deployment
    spec:
      containers:
      - name: nginx-zon-coffee
        image: learndevops16/webappb100:latest # Nginx container image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # Select pods with the label "app: nginx"
  ports:
  - protocol: TCP
    port: 80 # Port exposed by the service
    targetPort: 80 # Port to forward traffic to in the pods
  type: LoadBalancer
---
